# Generated by Django 5.1.5 on 2025-01-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profil',
            new_name='profile',
        ),
    ]
