# Generated by Django 4.0.6 on 2025-02-10 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_send', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
