# Generated by Django 4.0.6 on 2025-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notification_link_id_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
